# Generated by Django 3.1.3 on 2020-12-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0003_auto_20201205_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
